reportmap = {
    'S': {
        'bios': 'players',
        'summary': 'stats_skaters_summary',
        'faceOffPercentageAll': 'stats_skaters_faceoff',
        'timeOnIce': 'stats_skaters_timeonice',
        'points': 'stats_skaters_points'
    }, 'G': {
        'goalieBios': 'players',
        'summary': 'stats_goalies_summary',
        'specialTeamSaves': 'stats_goalies_special'
    }
}

fieldmap = {
    'games': {
        'attendance': 'Att',
        'season': 'Season',
        'game_type': 'Game Type',
        'game_id': 'Game ID',
        'game_date': 'Date',
        'home': 'Home',
        'visitor': 'Visitor',
        'overtime': 'Overtime',
        'shootout': 'Shootout',
        'hscore': 'Scr',
        'vscore': 'Scr, 1'
    }, 'stats_skaters_summary': {
        'player_id': 'Player ID',
        'season': 'Season',
        'game_type': 'Game Type',
        'gp': 'GP',
        'g': 'G',
        'a': 'A',
        'p': 'P',
        'plusminus': '+/-',
        'pim': 'PIM',
        'ppg': 'PPG',
        'shg': 'SHG',
        'shp': 'SHP',
        'gw': 'GW',
        'ot': 'OT',
        's': 'S',
        's_pct': 'S%',
        'toi_g': 'TOI/G',
        'sft_g': 'Sft/G',
        'fo_pct': 'FO%'
    }, 'stats_skaters_faceoff': {
        'player_id': 'Player ID',
        'season': 'Season',
        'game_type': 'Game Type',
        'gp': 'GP',
        'fo': 'Tot',
        'fow': 'FOW',
        'fol': 'FOL',
        'esfow': 'ESFOW',
        'esfol': 'ESFOL',
        'ppfow': 'PPFOW',
        'ppfol': 'PPFOL',
        'shfow': 'SHFOW',
        'shfol': 'SHFOL',
        'hfow': 'HFOW',
        'hfol': 'HFOL',
        'rfow': 'RFOW',
        'rfol': 'RFOL'
    }, 'stats_skaters_points': {
        'player_id': 'Player ID',
        'season': 'Season',
        'game_type': 'Game Type',
        'gp': 'GP',
        'g': 'G',
        'a': 'A',
        'p': 'P',
        'plusminus': '+/-',
        'esp': 'ESP',
        'shp': 'SHP',
        'hp': 'HmP',
        'rp': 'RdP',
        'dp': 'DvP',
        'ndp': 'ODvP',
        'p_g': 'P/G'
    }, 'stats_skaters_timeonice': {
        'player_id': 'Player ID',
        'season': 'Season',
        'game_type': 'Game Type',
        'gp': 'GP',
        'toi': 'TOI',
        'toi_g': 'TOI/G',
        'estoi': 'ES TOI',
        'estoi_g': 'ES TOI/G',
        'shtoi': 'SH TOI',
        'shtoi_g': 'SH TOI/G',
        'pptoi': 'PP TOI',
        'pptoi_g': 'PP TOI/G',
        'shifts': 'Shifts',
        'toi_shift': 'TOI/S',
        'shifts_g': 'Sft/G'
    }, 'stats_goalies_summary': {
        'player_id': 'Player ID',
        'season': 'Season',
        'game_type': 'Game Type',
        'gp': 'GP',
        'gs': 'GS',
        'w': 'W',
        'l': 'L',
        'ot': 'OT',
        'sa': 'SA',
        'ga': 'GA',
        'gaa': 'GAA',
        'sv': 'Sv',
        'svpct': 'Sv%',
        'so': 'SO',
        'g': 'G',
        'a': 'A',
        'pim': 'PIM',
        'toi': 'TOI',
    }, 'stats_goalies_special': {
        'player_id': 'Player ID',
        'season': 'Season',
        'game_type': 'Game Type',
        'gp': 'GP',
        'gs': 'GS',
        'ess': 'Even: SA',
        'esg': 'GA',
        'essv': 'Sv',
        'essvpct': 'Sv%',
        'pps': 'Power Play: SA',
        'ppg': 'GA, 1',
        'ppsv': 'Sv, 1',
        'ppsvpct': 'Sv%, 1',
        'shs': 'Shorthanded: SA',
        'shg': 'GA, 2',
        'shsv': 'Sv, 2',
        'shsvpct': 'Sv%, 2',
        'otgames': 'Overtime: GP',
        'ots': 'SA',
        'otg': 'GA, 3',
        'otsvpct': 'Sv%, 3',
        'otgaa': 'GAA'
    }, 'games_plays': {
        'game_id': 'game_id',
        'eventno': 'eventno',
        'period': 'period',
        'time_elapsed': 'time_elapsed',
        'time_game': 'time_game',
        'event_type': 'event_type',
        'description': 'description'
    }, 'games_plays_players': {
        'game_id': 'game_id',
        'eventno': 'eventno',
        'period': 'period',
        'team': 'team',
        'player_id': 'player_id'
    }, 'players': {
        'player_id': 'Player ID',
        'jersey': '#',
        'player_name': 'Player',
        'pos': 'Pos',
        'birthcity': 'Birth City',
        'state': 'S/P',
        'country': 'Ctry',
        'height': 'HT',
        'weight': 'Wt',
        'hand': 'S'
    }
}